name: manage-azure-policy
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
  push:
    paths:
      - .github/workflows/manage-azure-policy.yml      
      - 'policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**'
      - 'policies/Allowed_locations_for_resource_groups_e765b5de-1225-4ba3-bd56-1ac6695af988/**'
      - 'policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**'
      - 'policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**'
      - 'policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**'
      - 'policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**'
      - 'policies/Audit_Key_Vault_Location_AuditKeyVaultLocation/**'
      - 'policies/Azure_Cache_for_Redis_Append_a_specific_min_TLS_version_requirement_and_enforce_TLS._Append-Redis-sslEnforcement/**'
      - 'policies/Azure_Cache_for_Redis_Append_and_the_enforcement_that_enableNonSslPort_is_disabled._Append-Redis-disableNonSslPort/**'
      - 'policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**'
      - 'policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**'
      - 'policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**'
      - 'policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
      - 'policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/**'
      - 'policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**'
      - 'policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
      - 'policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**'
      - 'policies/Deny_vNet_peering_Deny-VNet-Peering/**'
      - 'policies/Deploy_a_user-defined_route_to_a_VNET_with_specific_routes._Deploy-Default-Udr/**'
      - 'policies/Deploy_an_Azure_DDoS_Protection_Standard_plan_Deploy-DDoSProtection/**'
      - 'policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**'
      - 'policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**'
      - 'policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**'
      - 'policies/Deploy_Azure_Defender_for_ARM_Deploy-ASC-Defender-ARM/**'
      - 'policies/Deploy_Azure_Defender_for_Azure_App_Services_Deploy-ASC-Defender-AppSrv/**'
      - 'policies/Deploy_Azure_Defender_for_Azure_Sql_Databases_Deploy-ASC-Defender-Sql/**'
      - 'policies/Deploy_Azure_Defender_for_DNS_Deploy-ASC-Defender-DNS/**'
      - 'policies/Deploy_Azure_Defender_for_Sql_on_Virtual_Machines_Deploy-ASC-Defender-SQLVM/**'
      - 'policies/Deploy_Azure_Defender_for_Storage_Accounts_Deploy-ASC-Defender-SA/**'
      - 'policies/Deploy_Azure_Defender_for_Virtual_Machines_Deploy-ASC-Defender-VMs/**'
      - 'policies/Deploy_Azure_Firewall_Manager_policy_in_the_subscription_Deploy-FirewallPolicy/**'
      - 'policies/Deploy_Azure_Security_Center_Security_Contacts_Deploy-ASC-SecurityContacts/**'
      - 'policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**'
      - 'policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**'
      - 'policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**'
      - 'policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**'
      - 'policies/Deploy_Windows_Domain_Join_Extension_with_keyvault_configuration_Deploy-Windows-DomainJoin/**'
      - 'policies/Deploy-ASC-Standard_Deploy-ASC-Standard/**'
      - 'policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**'
      - 'policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**'
      - 'policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**'
      - 'policies/Network_interfaces_should_disable_IP_forwarding_88c0b9da-ce96-4b03-9635-f29a937e2900/**'
      - 'policies/Network_interfaces_should_not_have_public_IPs_83a86a26-fd1f-447c-b59d-e51f44264114/**'
      - 'policies/No_child_resources_in_Automation_Account_Deny-AA-child-resources/**'
      - 'policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**'
      - 'policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**'
      - 'policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**'
      - 'policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**'
      - 'policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**'
      - 'policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**'
      - 'policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**'
      - 'policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**'
      - 'policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**'
      - 'policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
      - 'policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**'
      - 'policies/Require_a_tag_on_resources_871b6d14-10aa-478d-b590-94f262ecfa99/**'
      - 'policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
      - 'policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**'
      - 'policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**'
      - 'policies/Storage_Account_set_to_minimum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**'
      - 'policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**'
      - 'policies/Subnets_should_have_a_User_Defined_Route_Deny-Subnet-Without-UDR/**'
      - 'policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**'
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**
          policies/Allowed_locations_for_resource_groups_e765b5de-1225-4ba3-bd56-1ac6695af988/**
          policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**
          policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**
          policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**
          policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**
          policies/Audit_Key_Vault_Location_AuditKeyVaultLocation/**
          policies/Azure_Cache_for_Redis_Append_a_specific_min_TLS_version_requirement_and_enforce_TLS._Append-Redis-sslEnforcement/**
          policies/Azure_Cache_for_Redis_Append_and_the_enforcement_that_enableNonSslPort_is_disabled._Append-Redis-disableNonSslPort/**
          policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**
          policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**
          policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**
          policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/**
          policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**
          policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**
          policies/Deny_vNet_peering_Deny-VNet-Peering/**
          policies/Deploy_a_user-defined_route_to_a_VNET_with_specific_routes._Deploy-Default-Udr/**
          policies/Deploy_an_Azure_DDoS_Protection_Standard_plan_Deploy-DDoSProtection/**
          policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**
          policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**
          policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**
          policies/Deploy_Azure_Defender_for_ARM_Deploy-ASC-Defender-ARM/**
          policies/Deploy_Azure_Defender_for_Azure_App_Services_Deploy-ASC-Defender-AppSrv/**
          policies/Deploy_Azure_Defender_for_Azure_Sql_Databases_Deploy-ASC-Defender-Sql/**
          policies/Deploy_Azure_Defender_for_DNS_Deploy-ASC-Defender-DNS/**
          policies/Deploy_Azure_Defender_for_Sql_on_Virtual_Machines_Deploy-ASC-Defender-SQLVM/**
          policies/Deploy_Azure_Defender_for_Storage_Accounts_Deploy-ASC-Defender-SA/**
          policies/Deploy_Azure_Defender_for_Virtual_Machines_Deploy-ASC-Defender-VMs/**
          policies/Deploy_Azure_Firewall_Manager_policy_in_the_subscription_Deploy-FirewallPolicy/**
          policies/Deploy_Azure_Security_Center_Security_Contacts_Deploy-ASC-SecurityContacts/**
          policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**
          policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**
          policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**
          policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**
          policies/Deploy_Windows_Domain_Join_Extension_with_keyvault_configuration_Deploy-Windows-DomainJoin/**
          policies/Deploy-ASC-Standard_Deploy-ASC-Standard/**
          policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**
          policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**
          policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**
          policies/Network_interfaces_should_disable_IP_forwarding_88c0b9da-ce96-4b03-9635-f29a937e2900/**
          policies/Network_interfaces_should_not_have_public_IPs_83a86a26-fd1f-447c-b59d-e51f44264114/**
          policies/No_child_resources_in_Automation_Account_Deny-AA-child-resources/**
          policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**
          policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**
          policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**
          policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**
          policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**
          policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**
          policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**
          policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**
          policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**
          policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          policies/Require_a_tag_on_resource_groups_96670d01-0a4d-4649-9c89-2d3abc0a5025/**
          policies/Require_a_tag_on_resources_871b6d14-10aa-478d-b590-94f262ecfa99/**
          policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**
          policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**
          policies/Storage_Account_set_to_minimum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**
          policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**
          policies/Subnets_should_have_a_User_Defined_Route_Deny-Subnet-Without-UDR/**
          policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**
