name: manage-azure-policy-28662745
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_API_Apps_e9c8d085-d9cc-4b17-9cdc-059f1f01f19e/**'
#      - .github/workflows/manage-azure-policy-28662745.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_28662745}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**
          policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**
          policies/Remote_debugging_should_be_turned_off_for_API_Apps_e9c8d085-d9cc-4b17-9cdc-059f1f01f19e/**
