name: manage-azure-policy-6a85a1f6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**'
#      - .github/workflows/manage-azure-policy-6a85a1f6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6a85a1f6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**
