name: manage-azure-policy-1a0bd2ed
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_export_to_Event_Hub_for_Azure_Security_Center_data_cdfcce10-4578-4ecd-9703-530938e4abcb/**'
#      - .github/workflows/manage-azure-policy-1a0bd2ed.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1a0bd2ed}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_export_to_Event_Hub_for_Azure_Security_Center_data_cdfcce10-4578-4ecd-9703-530938e4abcb/**
